# Generated by Django 6.0.2 on 2026-02-16 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Kép címe')),
                ('image', models.ImageField(upload_to='photos/', verbose_name='Fénykép')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Feltöltés ideje')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tulajdonos')),
            ],
            options={
                'verbose_name': 'Fénykép',
                'verbose_name_plural': 'Fényképek',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
